const std = @import("std");
const api = @import("api");
const tc = @import("test_common.zig");

fn expectApproxEq(a: f64, b: f64) !void {
    try std.testing.expectApproxEqAbs(a, b, 1e-9);
}

test "fifo_realized: insert + read filters" {
    tc.vprint("fifo_realized: insert + read filters (new schema)");

    const handle = try tc.openMemDb();
    defer _ = api.zp_sqlite_close(handle);

    try tc.ensureFifoTables(handle);

    const buy_id_2024 = try tc.insertTradeReturnId(handle, "2024-01-01 10:00", "AAPL", "BUY");
    const sell_id_2024 = try tc.insertTradeReturnId(handle, "2024-06-01 10:00", "AAPL", "SELL");

    const buy_id_2025 = try tc.insertTradeReturnId(handle, "2025-01-10 10:00", "MSFT", "BUY");
    const sell_id_2025 = try tc.insertTradeReturnId(handle, "2025-07-10 10:00", "MSFT", "SELL");

    // -----------------------------
    // Insert row #1
    // -----------------------------
    var r1 = api.schema.zp_fifo_realized.zero();
    tc.setBufZ(r1.broker[0..], "IKBR");
    r1.tax_year = 2024;
    tc.setBufZ(r1.ticker[0..], "AAPL");
    tc.setBufZ(r1.country[0..], "PT");

    r1.sell_trade_id = sell_id_2024;
    r1.buy_trade_id = buy_id_2024;
    r1.match_seq = 1;

    tc.setBufZ(r1.sell_datetime[0..], "2024-06-01 10:00");
    tc.setBufZ(r1.buy_datetime[0..], "2024-01-01 10:00");

    r1.qty_matched = 1.0;

    // PT-oriented amounts (gain is generated by SQLite)
    r1.acquisition_value_eur = 100.0;
    r1.sale_value_eur = 120.0;
    r1.costs_eur = 0.0;

    // -----------------------------
    // Insert row #2
    // -----------------------------
    var r2 = api.schema.zp_fifo_realized.zero();
    tc.setBufZ(r2.broker[0..], "DEGIRO");
    r2.tax_year = 2025;
    tc.setBufZ(r2.ticker[0..], "MSFT");
    tc.setBufZ(r2.country[0..], "PT");

    r2.sell_trade_id = sell_id_2025;
    r2.buy_trade_id = buy_id_2025;
    r2.match_seq = 1;

    tc.setBufZ(r2.sell_datetime[0..], "2025-07-10 10:00");
    tc.setBufZ(r2.buy_datetime[0..], "2025-01-10 10:00");

    r2.qty_matched = 1.0;

    r2.acquisition_value_eur = 150.0;
    r2.sale_value_eur = 200.0;
    r2.costs_eur = 0.0;

    try std.testing.expectEqual(api.helper.ErrorCode.ok, api.zp_sqlite_insert_fifo_realized(handle, &r1));
    try std.testing.expectEqual(api.helper.ErrorCode.ok, api.zp_sqlite_insert_fifo_realized(handle, &r2));

    // -----------------------------
    // read_all
    // -----------------------------
    var out: [8]api.schema.zp_fifo_realized = undefined;
    var count: usize = 0;

    try std.testing.expectEqual(
        api.helper.ErrorCode.ok,
        api.zp_sqlite_read_fifo_realized_all(handle, &out, out.len, &count),
    );
    try std.testing.expectEqual(@as(usize, 2), count);

    // validate generated gain for both rows: gain = sale - acquisition - costs
    // (use approx because SQLite computes REAL)
    try expectApproxEq(out[0].gain_eur, out[0].sale_value_eur - out[0].acquisition_value_eur - out[0].costs_eur);
    try expectApproxEq(out[1].gain_eur, out[1].sale_value_eur - out[1].acquisition_value_eur - out[1].costs_eur);

    // Also validate expected gains from our constants (ordering is deterministic by ORDER BY)
    try expectApproxEq(out[0].gain_eur, 20.0);
    try expectApproxEq(out[1].gain_eur, 50.0);

    // -----------------------------
    // read_by_tax_year
    // -----------------------------
    var out_y: [8]api.schema.zp_fifo_realized = undefined;
    var count_y: usize = 0;

    try std.testing.expectEqual(
        api.helper.ErrorCode.ok,
        api.zp_sqlite_read_fifo_realized_by_tax_year(handle, 2024, &out_y, out_y.len, &count_y),
    );
    try std.testing.expectEqual(@as(usize, 1), count_y);
    try std.testing.expectEqualStrings("AAPL", tc.zstr(out_y[0].ticker[0..]));
    try std.testing.expectEqualStrings("PT", tc.zstr(out_y[0].country[0..]));
    try expectApproxEq(out_y[0].gain_eur, 20.0);

    // -----------------------------
    // read_by_ticker_per_year
    // -----------------------------
    var out_t: [8]api.schema.zp_fifo_realized = undefined;
    var count_t: usize = 0;

    try std.testing.expectEqual(
        api.helper.ErrorCode.ok,
        api.zp_sqlite_read_fifo_realized_by_ticker_per_year(handle, 2025, "MSFT", &out_t, out_t.len, &count_t),
    );
    try std.testing.expectEqual(@as(usize, 1), count_t);
    try std.testing.expectEqualStrings("DEGIRO", tc.zstr(out_t[0].broker[0..]));
    try std.testing.expectEqualStrings("PT", tc.zstr(out_t[0].country[0..]));
    try expectApproxEq(out_t[0].gain_eur, 50.0);

    // -----------------------------
    // read_by_broker_per_year
    // -----------------------------
    var out_b: [8]api.schema.zp_fifo_realized = undefined;
    var count_b: usize = 0;

    try std.testing.expectEqual(
        api.helper.ErrorCode.ok,
        api.zp_sqlite_read_fifo_realized_by_broker_per_year(handle, 2024, "IKBR", &out_b, out_b.len, &count_b),
    );
    try std.testing.expectEqual(@as(usize, 1), count_b);
    try std.testing.expectEqualStrings("AAPL", tc.zstr(out_b[0].ticker[0..]));
    try std.testing.expectEqualStrings("PT", tc.zstr(out_b[0].country[0..]));
    try expectApproxEq(out_b[0].gain_eur, 20.0);
}
